### ISSUE TITLE
Duplicate of aurelia-binding in webpack bundle

### ISSUE THREAD

**Issue by searus** [aurelia/framework#902]
Hi,

I experienced a strange issue yesterday when I updated an existing project to use Webpack 4.  I started seeing duplicated custom elements rendered and could see no reason for it.

Eventually, I managed to track it down to 2 instances of aurelia-binding being included in my bundle.  The second instance is included as an older version appears under node_modules/aurelia-templating-router/node_modules/aurelia-binding.

This confused me as I was not using the aurelia-router and the package was not included in my package.json.  It appears as though aurelia-framework has a reference to aurelia-templating-router that may be including the package in the build:
https://github.com/aurelia/framework/blob/3928b336e00937d9e33eb914d8a784759eeafd5b/dist/native-modules/aurelia-framework.js#L452

Please can you check this out and see if there's a problem?

Thanks

**Comment by searus** [comment]
Could this be related to #830 ??

**Comment by searus** [comment]
Here's a screen shot through dev tools to show the duplicate:

![image](https://user-images.githubusercontent.com/1336630/42303547-cf703714-8019-11e8-8b41-1e4f4e2f3105.png)

If I install aurelia-templating-router in my package then the problem goes away.

**Comment by Alexander-Taran** [comment]
Update aurelia packages.. This is resolved.

**Comment by searus** [comment]
@Alexander-Taran  I am on the latest versions

**Comment by StrahilKazlachev** [comment]
You sure you don't have a *lock* file?

**Comment by searus** [comment]
I think you're right... I was getting the wrong version from aurelia-dialog I believe.  Thanks!

**Comment by StrahilKazlachev** [comment]
`aurelia-dialog` is still not updated, sorry. Will try this week.

**Comment by searus** [comment]
No need to apologise... you guys are great and I appreciate everything coming from the Aurelia team!!
